version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda-latest"
  jobs:
    pre_build:
      # Download DSPS SSP data and LSST filter curves
      - mkdir -p dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/ssp-data-v1/fsps_v0.4.7_mist_c3k_a_kroupa_wNE_logGasU-2.0_logGasZ0.0.sparse.h5 -P dsps_drn
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_u_transmission.h5 -P dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_g_transmission.h5 -P dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_r_transmission.h5 -P dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_i_transmission.h5 -P dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_z_transmission.h5 -P dsps_drn/filters
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/filters-v1/lsst_y_transmission.h5 -P dsps_drn/filters
      - export DSPS_DRN="dsps_drn"

      # Download a pre-computed example mock for use in demo notebooks
      - mkdir -p docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/hacc-data-lastjourney-v1/lc_cores-decomposition.txt -P docs/source/mock_download_dir

      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/diffsky_cosmos_260316_05_03_2026_param_collection.hdf5 -P docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/diffsky_cosmos_260316_05_03_2026_ssp_data.hdf5 -P docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/diffsky_cosmos_260316_05_03_2026_transmission_curves.hdf5 -P docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/diffsky_cosmos_260316_05_03_2026_t_table.hdf5 -P docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/lc_cores-442.0.diffsky_gals.hdf5 -P docs/source/mock_download_dir
      - wget -q https://github.com/ArgonneCPAC/diffsky-data/releases/download/mock-galaxies-v1/lc_cores-453.0.diffsky_gals.hdf5 -P docs/source/mock_download_dir

      # # Generate the mock
      # - export DSPS_DRN="${PWD}/dsps_drn" && python scripts/LJ_LC_MOCKS/make_lj_mock.py scripts/LJ_LC_MOCKS/testing_lj_mock_config.yaml
      # - export DSPS_DRN="${PWD}/dsps_drn" && python scripts/LJ_LC_MOCKS/create_dummy_mock_data.py ci_test_output/dummy_version_name

      # # Copy mock data to where the notebook expects it
      # - cp ci_test_output/dummy_version_name/* docs/source/mock_download_dir/

      # Use the toolkit to create OpenCosmo-formatted data
      - mkdir -p docs/source/oc_download_dir
      - diffpipe run docs/source/mock_download_dir docs/source/oc_download_dir -n 2
      - cp docs/source/mock_download_dir/diffsky_*.hdf5 docs/source/oc_download_dir/
      - cp docs/source/mock_download_dir/lc_cores-decomposition.txt docs/source/oc_download_dir/

  environment:
      DSPS_DRN: "dsps_drn"

conda:
  environment: docs/source/rtd_environment.yaml

python:
  install:
    - method: pip
      path: .