name: rtd311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandoc>=3.1,<4.0
  - nbsphinx
  - jupyter
  - matplotlib
  - sphinx=7.2.4
  - sphinx-copybutton
  - numpy
  - jax
  - jaxlib
  - diffmah>=0.7.2
  - diffstar>=1.0.0
  - dsps>=0.4.5
  - h5py
