name: rtd312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandoc>=3.1,<4.0
  - pip
  - nbsphinx
  - jupyter
  - matplotlib
  - sphinx=7.2.4
  - sphinx-copybutton
  - numpy>=2
  - jax
  - jaxlib
  - diffmah>=0.7.2
  - diffstar>=1.0.0
  - dsps>=0.4.5
  - h5py
  - mpi4py
  - mpich
  - pip:
    - git+https://github.com/AstroPatty/diffpipe.git
    - git+https://github.com/ArgonneCPAC/opencosmo.git