name: test-main-branch-diffstuff

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: test-main-branch-diffstuff
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: configure conda and install code
      # Test against current main branch of all diff+ dependencies
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.CPAC_PRIVATE_REPO_TOKEN }}
          GITHUB_USER: ${{ secrets.GH_USR_TESTING_TOKEN }}

      # Test against conda-forge for all dependencies except use main branch for dsps
        run: |
          conda config --set always_yes yes
          conda install --quiet \
            --file=requirements.txt
          conda install -y -q \
            flake8 \
            pytest \
            pytest-xdist \
            pytest-cov \
            pip \
            setuptools \
            "setuptools_scm>=7,<8" \
            matplotlib \
            astropy \
            python-build
          pip uninstall diffmah --yes
          pip uninstall diffstar --yes
          pip uninstall dsps --yes
          pip install --no-deps git+https://github.com/ArgonneCPAC/diffmah.git
          pip install --no-deps git+https://github.com/ArgonneCPAC/diffstar.git
          pip install --no-deps git+https://github.com/ArgonneCPAC/dsps.git
          pip install --no-deps git+https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/ArgonneCPAC/diffstarpop.git
          python -m pip install --no-build-isolation --no-deps -e .

      - name: test
        shell: bash -l {0}
        run: |
          pytest -v diffsky --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: test versions
        shell: bash -el {0}
        run: |
          pip uninstall diffsky --yes
          [[ $(python setup.py --version) != "0.0.0" ]] || exit 1

          rm -rf dist/*
          python setup.py sdist
          pip install --no-deps --no-build-isolation dist/*.tar.gz
          pushd ..
          python -c "import diffsky; assert diffsky.__version__ != '0.0.0'"
          popd
          pip uninstall diffsky --yes

          rm -rf dist/*
          python -m build --sdist . --outdir dist
          pip install --no-deps --no-build-isolation dist/*.tar.gz
          pushd ..
          python -c "import diffsky; assert diffsky.__version__ != '0.0.0'"
          popd
          pip uninstall diffsky --yes

          python -m pip install -v --no-deps --no-build-isolation -e .
